% Complete THOMSON document profile.

\part{The electromagnetic field}
\chapter{The plane wave electromagnetic field}\label{ch:plane_wave}
\input{\srcpath/elm_field/plane_wave/plane_wave.tex}
\input{\srcpath/elm_field/plane_wave/gauge_invariance_of_plane_wave.tex}
\input{\srcpath/elm_field/plane_wave/Faraday_tensor_of_the_plane_wave.tex}
\input{\srcpath/elm_field/plane_wave/Lorenz_Coulomb_plane_wave.tex}
\chapter{The Laguerre-Gaussian modes of the electromagnetic field}
\input{\srcpath/elm_field/LG_modes/LG_modes.tex}

\part{Classical trajectory}
\setcounter{chapter}{0}
\chapter{Elements of relativistic dynamics}
\input{\srcpath/classical_motion/Lagrangean_theory/Lagrangean_theory.tex}

\chapter{Classical relativistic motion in a plane wave field}
\input{\srcpath/classical_motion/motion_in_pw/initial_conditions.tex}
\input{\srcpath/classical_motion/motion_in_pw/trajectory_in_arbitrary_pw.tex}

\part{The radiation scattering - time domain}
\setcounter{chapter}{0}
\chapter{The time domain results for single electron scattering}
\input{\srcpath/elm_el_sc/time-domain/c1.tex}
\chapter{The long distance approximation of the observables}
\input{\srcpath/elm_el_sc/time-domain/c2.tex}
\input{\srcpath/elm_el_sc/time-domain/c3.tex}

\part{The radiation scattering - Frequency domain}
\setcounter{chapter}{0}
\input{\srcpath/elm_el_sc/frequency-domain/FT-simplified.tex}

\part{{\color{red} The radiation scattering - frequency domain - INCOMPLETE}  }
\setcounter{chapter}{0}
\input{\srcpath/elm_el_sc/frequency-domain/c1.tex}
\input{\srcpath/elm_el_sc/frequency-domain/c2-f.tex}
\input{\srcpath/elm_el_sc/frequency-domain/c2.tex}
\input{\srcpath/elm_el_sc/frequency-domain/c2f-num.tex}
\input{\srcpath/elm_el_sc/frequency-domain/c3.tex}
\input{\srcpath/elm_el_sc/frequency-domain/c4.tex}
\input{\srcpath/elm_el_sc/frequency-domain/exact_Fourier_transforms.tex}

\part{\color{red}{Applications - INCOMPLETE}}
\setcounter{chapter}{0}
\chapter{The coherent Thomson scattering: LPWA for particles in circular motion}
\input{\srcpath/coherent_thomson/lpwa-lg-circular_motion.tex}

\chapter{The motion of a single particle in a plane wave with smooth turn-on}
\input{\srcpath/elm_field/plane_wave/smooth-mono.tex}
\input{\srcpath/classical_motion/motion_in_pw/uniparticle-smooth.tex}

\chapter[Coherent Thomson scattering in a circularly polarized LG mode]{Coherent Thomson scattering from particles injected head-on into a circularly polarized Laguerre--Gaussian mode within the local plane-wave approximation}
\input{\srcpath/coherent_thomson/lpwa-lg-circular_pol_head_on-sec1.tex}
\input{\srcpath/coherent_thomson/lpwa-lg-circular_pol_head_on-sec2.tex}
