% Complete THOMSON document profile.

\part{The electromagnetic field}
\chapter{The plane wave electromagnetic field}\label{ch:plane_wave}
\input{\srcpath/elm_field/plane_wave/plane_wave.tex}
\input{\srcpath/elm_field/plane_wave/gauge_invariance_of_plane_wave.tex}
\input{\srcpath/elm_field/plane_wave/Faraday_tensor_of_the_plane_wave.tex}
\input{\srcpath/elm_field/plane_wave/Lorenz_Coulomb_plane_wave.tex}
\chapter{The Laguerre-Gaussian modes of the electromagnetic field}
\input{\srcpath/elm_field/LG_modes/LG_modes.tex}

\part{Classical trajectory}
\setcounter{chapter}{0}
\chapter{Elements of relativistic dynamics}
\input{\srcpath/classical_motion/Lagrangean_theory/Lagrangean_theory.tex}

\part{The radiation scattering - time domain}
\setcounter{chapter}{0}
\chapter{The time domain results for single electron scattering}
\input{\srcpath/elm_el_sc/time-domain/c1.tex}

\part{The radiation scattering - Frequency domain}
\setcounter{chapter}{0}
\chapter{The Fourier transform of the emitted radiation}
\input{\srcpath/elm_el_sc/frequency-domain/FT-direct.tex}
\newpage
\input{\srcpath/elm_el_sc/frequency-domain/FT-simplified.tex}
\newpage
\input{\srcpath/elm_el_sc/frequency-domain/FT_simplified-numeric.tex}

\part{calculation of the observables}
\setcounter{chapter}{0}
\chapter{the energy density and the Poynting vector}
\input{\srcpath/calculation_of_observables_in_coherent_thomson/energy-density.tex}
\newpage
\input{\srcpath/calculation_of_observables_in_coherent_thomson/the_poynting_vector.tex}
\chapter{the linear momentum density and the linear momentum flux}
\input{\srcpath/calculation_of_observables_in_coherent_thomson/linear-momentum-density.tex}
\newpage
\input{\srcpath/calculation_of_observables_in_coherent_thomson/linear-momentum-flux-density.tex}

\chapter{the angular momentum density and the flux of angular momentum}
\begin{importantbox}
  In this chapter, we are concerned with the third component of angular
  momentum, $\mathcal J_3$, and with its flux in the $x_3$ direction,
  described by $\mathcal M_{33}$.
\end{importantbox}
\input{\srcpath/calculation_of_observables_in_coherent_thomson/angular-momentum-general-defintions.tex}
\newpage
\input{\srcpath/calculation_of_observables_in_coherent_thomson/orbital_angular_momentum.tex}
\newpage
\input{\srcpath/calculation_of_observables_in_coherent_thomson/spin_angular_momentum.tex}
\newpage

