% Complete THOMSON document profile.

\part{\color{red}{Applications - INCOMPLETE}}
\setcounter{chapter}{0}
\chapter{The coherent Thomson scattering: LPWA for particles in circular motion}
\input{\srcpath/coherent_thomson/lpwa-lg-circular_motion.tex}

\chapter{The motion of a single particle in a plane wave with smooth turn-on}
\input{\srcpath/elm_field/plane_wave/smooth-mono.tex}
\input{\srcpath/classical_motion/motion_in_pw/uniparticle-smooth.tex}

\chapter[Coherent Thomson scattering in a circularly polarized LG mode]{Coherent Thomson scattering from particles injected head-on into a circularly polarized Laguerre--Gaussian mode within the local plane-wave approximation}
\input{\srcpath/coherent_thomson/lpwa-lg-circular_pol_head_on-sec1.tex}
\input{\srcpath/coherent_thomson/lpwa-lg-circular_pol_head_on-sec2.tex}
\input{\srcpath/coherent_thomson/lpwa-lg-circular_pol_head_on-sec3.tex}
