\part{the one-absorber system}

\chapter{general description}
\input{\srcpath/mott_problem/one_absorber_description.tex}

\chapter{perturbative approach}
\input{\srcpath/mott_problem/one_absorber_perturbative.tex}

\chapter{numerical solution}
\input{\srcpath/mott_problem/one_absorber_numerical.tex}

\part{the two-absorber system}

\chapter{perturbative approach}
\input{\srcpath/mott_problem/two-absorbers-perturbative-o1.tex}
\input{\srcpath/mott_problem/two-absorbers-perturbative-o2.tex}

\chapter{numerical solution}
\input{\srcpath/mott_problem/two_absorbers_numerical.tex}

\part{appendix}
\appendix

\chapter{time dependent perturbation theory}
\input{\srcpath/mott_problem/tdpt.tex}

\chapter{the harmonic 1D oscillator}
\input{\srcpath/mott_problem/olh.tex}
\newpage
\input{\srcpath/mott_problem/olh-properties-1.tex}
\newpage
\input{\srcpath/mott_problem/olh-properties-2.tex}

\chapter{mathematical appendix}
\input{\srcpath/mott_problem/math.tex}
\input{\srcpath/mott_problem/regularization.tex}





