\part{general time-dependent perturbation theory}\label{part-general-tdpt}

\chapter{the Dyson series and transition amplitudes}
\input{\srcpath/mott_problem/part1_general/tdpt.tex}

\chapter{the projectile wave packet}
\input{\srcpath/mott_problem/part1_general/projectile_wavepacket.tex}

\setcounter{chapter}{0}
\part{continuous-position atoms: the linear oscillator}\label{part-continuous-atoms}

\chapter{the one-dimensional harmonic oscillator}
\input{\srcpath/mott_problem/part2_continuous_atoms/olh.tex}
\newpage
\input{\srcpath/mott_problem/part2_continuous_atoms/olh-properties-1.tex}
\newpage
\input{\srcpath/mott_problem/part2_continuous_atoms/olh-properties-2.tex}

\chapter{the one-absorber system}
\input{\srcpath/mott_problem/part2_continuous_atoms/one_absorber_description.tex}
\input{\srcpath/mott_problem/part2_continuous_atoms/one_absorber_perturbative.tex}
\input{\srcpath/mott_problem/part2_continuous_atoms/one_absorber_numerical.tex}

\chapter{the two-absorber system}
\input{\srcpath/mott_problem/part2_continuous_atoms/two_absorber_description.tex}
\input{\srcpath/mott_problem/part2_continuous_atoms/two-absorbers-perturbative-o1.tex}
\input{\srcpath/mott_problem/part2_continuous_atoms/two-absorbers-perturbative-o2.tex}
\input{\srcpath/mott_problem/part2_continuous_atoms/two_absorbers_numerical.tex}

\part{discrete-position atoms: two-level and few-level systems}\label{part-discrete-atoms}

\chapter{overview}
\input{\srcpath/mott_problem/part3_discrete_atoms/overview.tex}

\part{appendix}
\appendix

\chapter{mathematical identities}
\input{\srcpath/mott_problem/part4_appendix/math.tex}

\chapter{numerically stable energy factors}
\input{\srcpath/mott_problem/part4_appendix/regularization.tex}
